### ISSUE TITLE
mozilla-extension-manager fails to retrieve em:id with tree style tab addon

### ISSUE THREAD

**Issue by soredake** [NicolasBernaerts/ubuntu-scripts#14]
mozilla-extension-manager --user --install https://addons.mozilla.org/firefox/downloads/file/453945/tree_style_tab-0.17.2016061501-fx.xpi?src=dp-btn-primary
```
grep 'em:id=' install.rdf                                 
                   em:id="treestyletab@piro.sakura.ne.jp"
      <RDF:Description em:id="{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
```

**Comment by NicolasBernaerts** [comment]
This extension manifest is malformed.
<RDF:RDF>
<RDF:Description RDF:about="urn:mozilla:install-manifest" em:id="treestyletab@piro.sakura.ne.jp" em:name="Tree Style Tab" em:version="0.17.2016061501" em:creator="YUKI "Piro" Hiroshi" em:description="Show tabs like a tree." em:homepageURL="http://piro.sakura.ne.jp/xul/_treestyletab.html.en" em:iconURL="chrome://treestyletab/content/res/icon.png" em:optionsURL="chrome://treestyletab/content/config.xul" em:type="2" em:multiprocessCompatible="true">

All other extensions manifest look like :
<RDF>
<Description about="urn:mozilla:install-manifest">
<em:id>{ada4b710-8346-4b82-8199-5de2b400a6ae}</em:id>
<em:name>ReminderFox</em:name>
<em:version>2.1.5.5.3</em:version>

That's why it is not read properly.
