### ISSUE TITLE
Video is encoded in terribly low kbps

### ISSUE THREAD

**Issue by Aslanex** [NicolasBernaerts/ubuntu-scripts#8]
The video stabilizer encodes videos in about 20 mbps, no matter what was selected. As a result, the video is useless.

**Comment by Aslanex** [comment]
I analyzed it a bit, and it seems to ignore any zeros in the video-bitrate field - so 20000 becomes 2, 8000 becomes 8 and so on.

**Comment by NicolasBernaerts** [comment]
You are right, there is a trouble with YAD result with encoding values higher than 1000.
It must have come from a package update.
In fact, now YAD returns numeric values as 2,05e+04 instead of 20500. That's why you got values like 2.
I've added a scientific to normal conversion on the video bitrate result.
As other numeric values are lower than 1000, no need for them.
Latest script V3.7 should correct the bug.

**Comment by Aslanex** [comment]
Thanks, it works now.
